### ISSUE TITLE
Hunger/thirst bar NPE after respawning

### ISSUE THREAD

**Issue by rzats** [Terasology/JoshariasSurvival#14]
Respawning after dying with JS active results in a crash to desktop. This can be reliably reproduced.

Error message (full stacktrace @ http://pastebin.com/9TUfsz9x):

``` java
01:06:41.856 [main] ERROR o.terasology.engine.TerasologyEngine - Uncaught exception, attempting clean game shutdown
java.lang.NullPointerException: null
    at org.terasology.hunger.ui.HungerAndThirstWindow$1.get(HungerAndThirstWindow.java:41)
    at org.terasology.hunger.ui.HungerAndThirstWindow$1.get(HungerAndThirstWindow.java:36)
    at org.terasology.rendering.nui.widgets.UILoadBar.getValue(UILoadBar.java:102)
    at org.terasology.rendering.nui.widgets.UILoadBar.onDraw(UILoadBar.java:47)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.layouts.relative.RelativeLayout.onDraw(RelativeLayout.java:78)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.layers.hud.CoreHudWidget.onDraw(CoreHudWidget.java:60)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.layers.hud.HUDScreenLayer.onDraw(HUDScreenLayer.java:162)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawStyledWidget(CanvasImpl.java:406)
    at org.terasology.rendering.nui.internal.CanvasImpl.drawWidget(CanvasImpl.java:392)
    at org.terasology.rendering.nui.internal.NUIManagerInternal.render(NUIManagerInternal.java:468)
    at org.terasology.engine.modes.StateIngame.renderUserInterface(StateIngame.java:234)
    at org.terasology.engine.modes.StateIngame.render(StateIngame.java:218)
    at org.terasology.engine.subsystem.lwjgl.LwjglGraphics.postUpdate(LwjglGraphics.java:189)
    at org.terasology.engine.TerasologyEngine.mainLoop(TerasologyEngine.java:423)
    at org.terasology.engine.TerasologyEngine.run(TerasologyEngine.java:369)
    at org.terasology.engine.Terasology.main(Terasology.java:150)
```

**Comment by Cervator** [comment]
Bump - still active. My character got to near starvation having left it on a JS-enabled server overnight. Logged in, finished starving to death after a minute or so, respawned, crash :-)

**Comment by Cervator** [comment]
Confirmed fixed! Thanks @rzats :-)
